jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@master
        with:
          nix_conf: |
            extra-experimental-features = recursive-nix
            extra-system-features = recursive-nix
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: a-single-key
      - run: nix flake --accept-flake-config check --print-build-logs --keep-going
on:
  push: {}
  workflow_call: {}
